<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * GroupsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByUser(User $user)
    {
        $qb = $this->_em->createQueryBuilder();
        $query = $qb->select('g')
            ->from('AppBundle:Groups', 'g')
            ->join('AppBundle:UserGroup', 'j')
            ->where('g.id = j.group')
            ->andWhere('j.user = :user')
            ->setParameter('user', $user)
            ->getQuery();

        return $query->getResult();
    }
}
