<?php

namespace AppBundle\Repository;

/**
 * GroupsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupsRepository extends \Doctrine\ORM\EntityRepository
{
}
