<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * LoginRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoginRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $string
     * @return array
     */
    public function findByLetters($string, User $user)
    {
        $qb = $this->_em->createQueryBuilder();
        $query = $qb->select('l')
            ->from('AppBundle:Login', 'l')
            ->join('l.group', 'g')
            ->join('AppBundle:UserGroup', 'j')
            ->Where('g.id = j.group')
            ->andWhere('j.user = :user')
            ->andWhere('(l.name LIKE :string OR l.url LIKE :string)')
            ->setParameter('user', $user)
            ->setParameter('string', '%'.$string.'%')
            ->getQuery();

        return $query->getResult();

    }

    public function findAllByUser(User $user)
    {

        $qb = $this->_em->createQueryBuilder();
        $query = $qb->select('l')
            ->from('AppBundle:Login', 'l')
            ->join('l.group', 'g')
            ->join('AppBundle:UserGroup', 'j')
            ->Where('g.id = j.group')
            ->andWhere('j.user = :user')
            ->setParameter('user', $user)
            ->getQuery();

        return $query->getResult();
    }

}
