<?php

namespace AppBundle\Repository;

/**
 * LoginRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoginRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByLetters($string)
    {
        return $this->getEntityManager()->createQuery('SELECT l FROM AppBundle:Login l
                WHERE l.name LIKE :string
                 OR l.url LIKE :string')
            ->setParameter('string','%'.$string.'%')
            ->getResult();
    }
}
