<?php

namespace AppBundle\Repository;

/**
 * LoginRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoginRepository extends \Doctrine\ORM\EntityRepository
{
}
